#!/usr/bin/env python3
import time

DEVICE_PATH = "/sys/bus/w1/devices/28-0000074b57ed/w1_slave"

while True:
    time.sleep(2)

    with open(DEVICE_PATH, "r") as f:
        inhalt = f.read()

    if "YES" not in inhalt.splitlines()[0]:
        continue

    tempdata = inhalt.split("\n")[1].split(" ")[9]
    temperatur = float(tempdata[2:]) / 1000

    print(f"Temperatur beträgt: {temperatur:.3f} °C")
